[package]
name = "forestry"
version = "0.1.0"
edition = "2024"

[dependencies]
auth-git2 = "0.5.8"
color-eyre = "0.6.5"
crossterm = { version = "0.28.0", features = ["event-stream"] }
futures = "0.3.32"
git2 = "0.20.2"
ratatui = "0.29.0"
regex = "1.11"
throbber-widgets-tui = "0.9.0"
tokio = { version = "1", features = ["full"] }
tokio-util = "0.7.18"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tui-input = "0.14.0"
